version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Navigating to frontend directory and installing dependencies..."
      - cd Pol-Kole-Frontend
      - npm ci

  build:
    commands:
      - echo "Building Angular application in production mode..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: Pol-Kole-Frontend/dist/Pol-Kole-Frontend/browser

cache:
  paths:
    - 'Pol-Kole-Frontend/node_modules/**/*'
